/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f401re.h"
#include "timer.h"
#include "Ucglib.h"

static ucg_t ucg;

#define LCD_BG_R                6u
#define LCD_BG_G                18u
#define LCD_BG_B                48u

#define LCD_TEXT_R              255u
#define LCD_TEXT_G              255u
#define LCD_TEXT_B              255u

#define LCD_TEXT_X              0
#define LCD_TEXT_Y              12
#define LCD_LINE_SPACING        14

#define LCD_FONT                ucg_font_ncenR12_hr
#define LCD_LINE1               "I love Embedded"
#define LCD_LINE2               "Programming"

static void lcd_Setup(void)
{
    ucg_SetColor(&ucg, 0, LCD_BG_R, LCD_BG_G, LCD_BG_B);
    ucg_ClearScreen(&ucg);

    ucg_SetFont(&ucg, LCD_FONT);
    ucg_SetColor(&ucg, 0, LCD_TEXT_R, LCD_TEXT_G, LCD_TEXT_B);
    ucg_SetColor(&ucg, 1, LCD_BG_R, LCD_BG_G, LCD_BG_B);
    ucg_SetRotate180(&ucg);
    ucg_DrawString(&ucg, LCD_TEXT_X, LCD_TEXT_Y, 0, LCD_LINE1);
    ucg_DrawString(&ucg, LCD_TEXT_X, LCD_TEXT_Y + LCD_LINE_SPACING, 0, LCD_LINE2);

}

int main(void)
{
    SystemCoreClockUpdate();
    TimerInit();
    Ucglib4WireSWSPI_begin(&ucg, UCG_FONT_MODE_SOLID);
    lcd_Setup();
	while(1)
	{
		processTimerScheduler();
	}
    for (;;) {
    }
}
