/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f401re.h"
#include "stm32f401re_gpio.h"
#include "stm32f401re_rcc.h"

#define LED_PORT                GPIOA
#define LED_PIN                 GPIO_Pin_5

volatile uint32_t g_gpioa_ahb1enr_snapshot = 0u;
volatile uint32_t g_gpioa_clock_enabled = 0u;
volatile uint32_t g_gpioa_bus_is_ahb1 = 1u;

static void Delay(volatile uint32_t cycles)
{
    while (cycles-- != 0u) {
        __asm volatile ("nop");
    }
}

static void enable_Gpioa_Clock(void)
{
    SystemCoreClockUpdate();

    /* Method 2: enable GPIOA clock manually in code via AHB1. */
    RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);

    /* These variables are convenient to inspect during debug. */
    g_gpioa_ahb1enr_snapshot = RCC->AHB1ENR;
    g_gpioa_clock_enabled = (RCC->AHB1ENR & RCC_AHB1ENR_GPIOAEN);
}

static void init_Led(void)
{
    GPIO_InitTypeDef gpio_init;

    gpio_init.GPIO_Pin = LED_PIN;
    gpio_init.GPIO_Mode = GPIO_Mode_OUT;
    gpio_init.GPIO_OType = GPIO_OType_PP;
    gpio_init.GPIO_PuPd = GPIO_PuPd_NOPULL;
    gpio_init.GPIO_Speed = GPIO_Speed_50MHz;

    GPIO_Init(LED_PORT, &gpio_init);
}

int main(void)
{
	enable_Gpioa_Clock();
	init_Led();

    for (;;) {
        GPIO_SetBits(LED_PORT, LED_PIN);
        Delay(SystemCoreClock / 8u);

        GPIO_ResetBits(LED_PORT, LED_PIN);
        Delay(SystemCoreClock / 8u);
    }
}
